# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        /:year/:month/:day/:title.html

# Setup
title:            Cogs and Levers
tagline:          'A blog full of technical stuff'
description:      'A place for thoughts, ideas, tutorials and bookmarks. My brain can only hold so much, you know.'
keywords:		  [ "Programming", "Technical", "Tutorials", "Learning", "Articles", "HOWTO" ]

url:              http://tuttlem.github.io

author:
  name:           'Michael Tuttle'
  url:            https://twitter.com/tuttlemr

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/tuttlem/tuttlem.github.io

timezone:         Australia/Brisbane